### PR TITLE
Fixing Loading Direction push pull Issues

### LINKED ISSUE #73: Pushing Area Loads Causes Error
#### Description:

The Push of UniformlyDistributedAreaLoad does error Message and does not Push the AreaLoad. 

#### Steps to reproduce:

The Error can be reporduced using the follwing Script. 
[Link](https://burohappold.sharepoint.com/:u:/s/BHoM/EetspdKfLHRMr5TOWAeOLXcByWZo0Hz5DGwx1tYqTiaZqA?e=trG4qU)

### LINKED ISSUE #75: Checking all Load Orintations
#### Description:

Load orientations are very error prawn. As a few cases came up with complaints this will require an fundamental check for all load types. 
This does include the: 
 - Nodal Load
 - GeometricalLineLoad (FreeLineload/Lineload)
 - Uniformly Destributed Area Load ()
 - BarLoad

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

With this PR orientation errors for the push pull of PointLoads, BarUniformlyDistributedLoads, AreaUnifromlyDistributedLoads and LineLoads (Both non-free and free) habe been reviewed, refactored and debugged. 

Closes #75 
Closes #73 

The anticipated resulte should be that All loads are pushed/pulled correctly. This referres to the loads: 

- Orientation
- Type (Moment vs. Force) 
- Magnitude
- Projektion
- Axis (LoadAxis is local or global)

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/s/BHoM/EVI1H5XzR7NGhmHSCR8xp7YBtZJt9FXmS-D0V7jNsuMoXA?e=O1R92w)

### Changelog

Refactoring and reviewing of conversion methods for: 
- PointLoads
- BarUniformlyDistributedLoads
- AreaUniformlyDistributedLoads
- GeometricalLineLoads

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by Kar-Myl — CHANGES_REQUESTED** [review]
When Pushing Uniformly Distributed Area Loads, the forces are created properly. However, when pulled, the information is not read properly. Loads that were projected while pushing do not appear as projected upon pulling.

**Comment by Kar-Myl** [comment]
In case of **Non-Free Geometric Line Loads** the following issues were found:

When Pushing:

- Unable to push more than 6 line loads.
- Projected feature doesn't work.

**Comment by Kar-Myl** [comment]
> When Pushing Uniformly Distributed Area Loads, the forces are created properly. However, when pulled, the information is not read properly. Loads that were projected while pushing do not appear as projected upon pulling.


Probably because loads being pushed had local axis. Works as expected when valid i.e., when Global axis is used.

**Comment by Kar-Myl** [comment]
In case of **Free Geometrical Line Loads**, when a curve and an object are given as inputs, loads are not being pushed.

image
image


However, when it is just the curve, loads are created as expected.

**Comment by Arne-Martensen** [comment]
> 

Have you checked if you have pushed the load with the correct LoadAxis? When Pushing with axis=LoadAxis.Local the values in RFEM6 will not be pushed as projected, as the Data Structure in RFEM6 does not allow "locals" to be projected.

**Comment by Arne-Martensen** [comment]
> When Pushing Uniformly Distributed Area Loads, the forces are created properly. However, when pulled, the information is not read properly. Loads that were projected while pushing do not appear as projected upon pulling.

@Kar-Myl  Have you made sure taht you are pushing a loads with axis=AxisLoad.Global when checking? AreaUniformlyDistributedLoads can only be pushed as prjected when the variable axis is set to AxisLoad.Global.

**Comment by Arne-Martensen** [comment]
> In case of **Non-Free Geometric Line Loads** the following issues were found:
> 
> When Pushing:
> 
> * Unable to push more than 6 line loads.
> * Projected feature doesn't work.

@Kar-Myl  Please Raise this an another Issue

**Comment by Kar-Myl** [comment]
> In case of **Free Geometrical Line Loads**, when a curve and an object are given as inputs, loads are not being pushed.
> 
> image image
> 
> However, when it is just the curve, loads are created as expected.

Issue now seems to be resolved.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
