### PR TITLE
Push And Pull Loadcases

### LINKED ISSUE #36: Push and Pull of Loadcases
#### Description:

Enable the RFEM6_Toolkit to pull and push Loadcases from and to BHoM.

### LINKED ISSUE #37: Push and Pull of Member Loads
#### Description:

Push and Pull of Member Loads

### LINKED ISSUE #39: Push and Pull of Point Loads
#### Description:

Enable the RFEM6_Toolkit to push and pull Point Loads from and to RFEM6.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

The current version of the RFEM6_Toolkit was unable to pull and push load cases or loads. This PR (Pull Request) represents the first step towards resolving this issue. Now, load cases can be both pulled and pushed. This also applies to point loads and uniformly distributed bar loads.

Closes #36 
Closes #37
Closes #39 

### Test files

[File Link](https://burohappold-my.sharepoint.com/:u:/p/arne_martensen/EaDiTQds949IiBEHqMX6tcUB9uZMJpgS7_wHBBwqQLD_ug?e=2dFPeW)

### Additional comments

It is importatnt to point our few things for the usage of the newly added features. 

1. The load cases defined in BHoM and RFEM6 do not have a one-to-one correspondence, particularly when it comes to live loads. While some adjustments might still be necessary, so far it has been functioning.
2. When pushing loads into an existing model, or even pushing loads twice, there is no 'update' functionality. All new loads will just be added on top of the existing model.

### CODE REVIEW

**Review by staintono — CHANGES_REQUESTED** [review]
The Pushing and Pulling of Loadcases, Point Loads and UDL Bar Loads was tested using the provided test script. 
Loadcases can be pushed successfully, however the number of the loadcase cannot be defined. This will be raised as a separate issue, as this does not affect the functionality. 
Point Loads defined in a single direction can be successfully pushed, however they are pushed incorrectly when a vector with components in various directions are defined, as well as provided an incorrect load size. 
The same applies to Bar UDLs. If bars are pushed as a separate element as well as being defined within the loads none of the loads get pushed.

**Review by staintono — DISMISSED** [review]
The same testing procedure as the previous review was used. Loadcases function as previously commented. Point Loads can be pushed and defined as a component vector and are pushed accordingly. Bar UDLs can now be correctly pushed. With multiple directions, the load is not pushed and an error is flagged to the user. The code was not reviewed

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by staintono — DISMISSED** [review]
Previous review is still valid. changes were only made to the text in the code

**Comment by Arne-Martensen** [comment]
@BHoMBot check serialisation
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check null-handling

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance
@BHoMBot check serialisation
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check null-handling

**Review by staintono — APPROVED** [review]
The same testing procedure as the previous review was used. Loadcases function as previously commented. Point Loads can be pushed and defined as a component vector and are pushed accordingly. Bar UDLs can now be correctly pushed. With multiple directions, the load is not pushed and an error is flagged to the user. The code was not reviewed

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
