### PR TITLE
Load Push Results In Error

### LINKED ISSUE #89: Error when Pushing Loads- LoadCases ID not existend
When pushing loads or load cases, the adapter attempts to call the next ID method. However, due to some RFEM6-specific issues, this is not an option. Despite that, the current version still performs this action, resulting in an error.

This is a bug that was detected during the Test Sprint for the BHoM 7.2

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

When pushing loads or load cases, the adapter attempts to call the next ID method. However, due to some RFEM6-specific issues, this is not an option. Despite that, the current version still performs this action, resulting in an error.

Closes #89 

With this PR the issue should be resolved and Loads should be able to be pushed without bigger problems. 

### Test files

[Link](https://burohappold.sharepoint.com/:u:/s/BHoM/ERGMfo0gDvFKjtb0kEFkILwBy_wKC2g6kyhsuJmfyCADxA?e=kondma)

### Changelog

- Changed `LoadCase.GetRFEMID()` to `LoadCase.Number` to prevent error.

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by Kar-Myl — APPROVED** [review]
The file was tested to see if the loads were being pushed and pulled properly. 

Loads were pushed to RFEM6 and then pulled back to verify if the same type of load was pulled back. 

Feature worked as expected. 

The code was not reviewed

**Comment by Arne-Martensen** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
