### PR TITLE
Read Nodal Support Reactions

### LINKED ISSUE #64: Read Nodal Loads
#### Description:

Enable the User to rad read results from nodal support.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

This pull request enables users to read nodal support reactions.

Closes #64 

### Test files

[Test Files](https://burohappold.sharepoint.com/:f:/s/BHoM/EgGi5l68tJhMntOS9SURBEMBejcPqUM3ZqQiILyPBZ7CgQ?e=wvWfPp)

### Changelog

- Added the partial ‘NodeReaction’ class.
- Implemented the ReadResults method.
- Added the ExtracNodeReaction method.

### Additional comments

- When pulling reactions, both the case and object inputs require lists of integer values. If no object is specified, all supports will be chosen.
- For the testing both an RFEM6 modell as well as a GH script have been created. You will need both for your test. 
- For testing, it is necessary to run the calculation of the RFEM6 model first.

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by Kar-Myl — APPROVED** [review]
Feature was tested on the file provided. It was additionally tested on a project file created in an older RFEM6 version. In both cases, the test procedure was as follows:

- Results for various load cases were calculated in RFEM6. 
- The nodal support results were pulled for various elements.  The pulled values were cross checked with the values displayed in RFEM6. 

In both cases, feature worked as expected.

Code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
