### PR TITLE
BarFEAType integraged into the RFEM6_Adapter

### LINKED ISSUE #27: BarFEAType integraged into the RFEM6_Adapter
#### Description:

Bars in the BHoM do have and feaType attribute. 

image

There is an equivalent reature to this in RFEM6. The RFEM6 Adapter should be able work with this feature to Beams/Members in RFEM6 by enableing the push and pull of those features.  

image

### LINKED ISSUE #35: Pull And Push Load Cases
#### Description:

The Pull and Push load cases for BHoM should be implemented in the RFEM6 Toolkit.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

Closes #27 
Closes #35 

With this PR the featrues of Pulling and Pushing FEATypes for Bars as well as the Pull and Push of LoadCases should be enables. 

Note: Not all Loadcases from BHoM do have a counterpart in RFEM6. e.g. the Loadcases with a Load Nature of type other will be interpreted as Deadload and the type of Notional will not be pushed at all. At this point the Loadcases are only implemented and tested for the EN 1990

### Test files

[TestFile](https://burohappold-my.sharepoint.com/:u:/p/arne_martensen/EapgB08Q6ClNiXflgPjwgCsBJgzIgnnq83PdGjyKek1tQg?e=3S4Dwa)

### Changelog

**FEATypes**
- Convert methond `ToRFEM6()` and `FromRFEM6()` for FEATypes
- Adding FEATypes to the Creat and Read Method for Bars

**LoadCase**
- Convert methond `ToRFEM6()` and `FromRFEM6()` for Loadcase
- Adding of a Creat and Read Method for Loadcases

### CODE REVIEW

**Review by staintono — APPROVED** [review]
The PR was reviewed using the provided Test script as well as user created tests. Bar Types can be successfully pushed and pulled. Loadcases can be successfully pulled and pushed. It was noted, that gravity loading is enabled for loadcase 1 without specifying it, this will be raised as a separate issue. The code was not reviewed

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 18043507141

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Pull request merged**
