### PR TITLE
Push pull of Nodes, Material, SectionProperties, Bars

### LINKED ISSUE #2: Push Pull of Nodes
#### Description:

The feature of pushing and Pulling Nodes from and to RFEM has to be added. 

To generate a test case, just create a BHoM node and try to push/and pull it from RFEM6 using the corresponding adapter plus the pull and push nodes.

### LINKED ISSUE #3: Pull and Push Material
#### Description:

The feature of pushing and Pulling Nodes from and to RFEM has to be added.

To generate a test case, just create a BHoM material and try to push/and pull it from RFEM6 using the corresponding adapter plus the pull and push nodes.

### LINKED ISSUE #4: Pull and Push of Cross Section
#### Description:

The feature of pushing and Pulling Cross Sections from and to RFEM has to be added.

To generate a test case, just create a BHoM Cross Section and try to push/and pull it from RFEM6 using the corresponding adapter plus the pull and push nodes.

### LINKED ISSUE #5: Pull and Push of Bars from and to RFEM6
#### Description:

The feature of pushing and Pulling Bars from and to RFEM6 has to be added.

To generate a test case, just create a BHoM Bar and try to push/and pull it from RFEM6 using the corresponding adapter plus the pull and push nodes.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

This PR is adressing the Push and Pull of differnt types of elemenst like nodes, Materials, Cross-Sections and Bars (defined by polylines). After the compilation the user should be enabled to push all, in BHoM defied standard Steelsecton from the EU and UK as well as non-standard crossection. 

Closes #2  
Closes #3 
Closes #4 
Closes #5   

### Test files

The test file below does test the push and pull of EU standard steel sections, UK standard steel sections as well as non standard concrete and steel sections. US standard sections have NOT been been handled yet.  
[Test File Push Pull Sections and Material](https://burohappold.sharepoint.com/:u:/s/BHoM/EWzwOHQpTFBPrdMLqfZ5twoBN5xFnGxitjDF4zczVN-77w?e=TRl64P)

The testfile below does test the Push and the pull of Beams with both standard and non-Standard section as well as nodal supports. 
[Test file Push an Pull of Beams](https://burohappold.sharepoint.com/:u:/s/BHoM/ESZ3mvqyHGJFmLnR18RXgZoBgeLnR8e5tdGJXR_329dlBg?e=mS7lua)
### Changelog

The following partial classes have been added to multiple folders within the RFEM6_Toolkit solution: 

- Bar
- Constraint
- Material
- Node
- SectionProperties

All above have been added to the 'Create' and 'Read' folder as well ass the 'Convert' folder for both the translation to RFEM6 (folder: ToRfem6) and from RFEM6(folder: FromRFEM6). 

### Additional comments

The Push of beams into RFEM6 is currently very low. The Code will still need to be reviewed an optimized.

### CODE REVIEW

**Review by staintono — APPROVED** [review]
Tested the Toolkit by pushing cross sections and bars using the test files provided, as well as creating bars and cross-sections outside of the test files. Everything is pushed and pulled as expected.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
check copyright-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check copyright-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check project-compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
as mentioned offline - The project compliance failure, requiring targeting some specific frameworks can safely be ignored for this case. The 4.8 framework is allowed to be used when required by an external package, which is the case here.

This can be merged with no updates to the framework in the project files.

**Review by staintono — APPROVED** [review]
The pushing and pulling of sections and bars works as expect. This has been tested using the test scripts provided. The accuracy of the data pushed has been spot checked for a couple of sections and not for all sections. The code has not been reviewed

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by staintono — APPROVED** [review]
The pushing and pulling of sections and bars works as expect. This has been tested using the test scripts provided. The accuracy of the data pushed has been spot checked for a couple of sections and not for all sections. The code has not been reviewed

**Pull request merged**
