### PR TITLE
Problem When Pushing Loads with and LoadCase which has alreacy been defined in RFEM6

### LINKED ISSUE #92: Problem When Pushing Loads with and LoadCase which has alreacy been defined in RFEM6
Push of Loads with and already existin LoadCase with an equivalent Nature results in an error messages and in the Load not beeing pushed into RFEM6.

### LINKED ISSUE #94: Reading Nodal Results from Excel Not working
#### Description:

When reading results Nodal Reactions via Excel the results cant be acessed.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

Push of Loads with and already existin LoadCase with an equivalent Nature results in an error messages and in the Load not beeing pushed into RFEM6.

Another minor issue that has been fixed was that the pull of nodal reactions was not possible from Excel due to some impossible casting to string. This has been taken care of. 

Closes #92 
Closes #94 

Comparars for both LoadCases well as Section have been modifies. For the Testing please just Push all gemetrical elements and after that push all loads. The result should be Geometry in RFEM6 and Loads plus appopriatly names and numberated Loadcasese. 

Please Try to read nodal loads from Both the GH file and the Excel File. 

### Test files

[Link GH Script ](https://burohappold.sharepoint.com/:u:/s/BHoM/EeRptLyQuVJGgG16ySfTZCkBgPrtMmzHBOmWtRaAGUEdzA?e=BG8aMy)
[Link Excel File](https://burohappold.sharepoint.com/:x:/s/BHoM/EWuacWUWhEBMuFw6mvtjaAcBAYh3nzN1ksnU_7rO8HFYdA?e=DVgFGP)

### Changelog

- Alteration of Comparer for Loadcases
-  Alteration of Comparer for Sections

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Review by Kar-Myl — DISMISSED** [review]
The provided grasshopper file was used in order to first push the geometry followed by multiple load cases. Pushing multiple load cases when loads were already present did not lead to errors. 
Later the pushed loads were pulled and nodal reactions were verified for multiple load cases.

Code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by Kar-Myl — APPROVED** [review]
The provided grasshopper file was used in order to first push the geometry followed by multiple load cases. Pushing multiple load cases when loads were already present did not lead to errors.
Later the pushed loads were pulled and nodal reactions were verified for multiple load cases.

Code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
