### PR TITLE
Push Pull of Panelloads and Lineloads

### LINKED ISSUE #38: Add Lineloads
#### Description:

Enable the pull and push of Lineloads between whon and RFEM6

### LINKED ISSUE #40: Pull and Push Surface Load
#### Description:

Enable the pull and push of Surface Loads from and to RFEM6

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

Closes #40 
Closes #38 

This PR should enable the user to both push and pull line loads and panel loads into RFEM6.

### Test files

[Testfile](https://burohappold.sharepoint.com/:u:/s/BHoM/EfylUtFi8chCsgq5lzz3jesB1enHSrh-P4MNRsA1lcxZkg?e=GCbVFm)

### Changelog

- Alteration of Create method. Added sections in charge of creation for Lineloads, Free Lineloads and UDL Arealoads. 
- Added Read Methods ReadLineLoad, ReadFreeLineLoad and ReadAreaLoad. 

### Additional comments

The push of both types of line loads and the area loads should take place in a two-stage push. This means that the push of the geometrical elements, such as panels, should occur in a previous push, while the push of the load itself should be carried out in a second push.

It is important to note that the loads will not be overwritten when altering (or not altering) loads and pushing them again. Generally, loads should always be defined using vectors parallel to the X, Y, or Z-axis.

In terms of load types, when pushing, Free Line Loads support only the 'Force' type due to restrictions in RFEM6 (this is not a BHoM issue). The 'Force' type can only be linear, which also includes uniformly distributed loads, over the entire line. In comparison, Line Loads support both Moments and Forces, but not in combination. The load distribution is trapezoidal over the entire line, which includes UDL (Uniformly Distributed Load) or linear load.

### CODE REVIEW

**Review by staintono — APPROVED** [review]
The PR was tested using the provided test script as well as some user changes to the script.
Geometrical Line Loads can successfully be pushed with the Free/NonFree Fragment added and works as expected. Area Loads can be pushed as surface loads.
The code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
