### PR TITLE
Push/Pull of Panel Outlines in Arc/Circle shapes

### LINKED ISSUE #15: Pushing of Model into RFEM6 not possible with incompatible materials/sections
#### Description:

When pushing into a non-empty RFEM6 model, the model is not able to be pushed. This is due to the existing materials and sections within the model not being recognised by the adapter/bhom, and therefore throwing an error.

#### Steps to reproduce:

Open the attached test RFEM file, and push a elements into this model. After pushing the nodes the error should arise. 

#### Expected behaviour:

Elements should be able to be pushed into a model with existing elements

#### Test file(s):

[Test File ](https://burohappold-my.sharepoint.com/:u:/g/personal/oliver_stainton_burohappold_com1/EfAs1B8uZdJDkij8PvTijkgBCif1Krgkni6Z6kGPsjqHAA?e=34cQT5)

### LINKED ISSUE #16: Push/Pull of Panel Outlines in Arc/Circle shapes
Currently only surfaces with a Polygonal shaped outline can be pushed and pulled. It should also be possible to push and pull Panels with a circular, Arched or a combined (arcs and lines combined) outline.

### LINKED ISSUE #17: Push/Pull of Surface Openings.
Opnings of Panels are not supported yet. The user should be able to both push and pull Openings in surfaces.

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

Currently only panels witha a polygonal outline can be pushed and pulled to and from RFEM6. This PR should enable the user to Pull and Push both panels with a circulare outline as well as panels with outlines that are a combination of arches and lines. 

Additionally to that after the merge of the corresponding branch the user should be enabled to pull and push openings of type circel, arc or line (or a combination of those).

This PR also enables users to pull materials or sections of a type that have not been implemented or are not part of the BHoM. For example, if a material has been defined in RFEM6 that does not have a corresponding definition in the BHoM, a GenericIsotropicMaterial will be generated with the original name, but all parameters will be set to 0. Similarly, when attempting to read a non-defined section, an Explicit section will be defined with the original name, but all parameters will be set to 0.

Closes #15
Closes #16
Closes #17

### Test files

[Test GH File](https://burohappold-my.sharepoint.com/:u:/p/arne_martensen/EejKSWaaZDZBqXhbw7ebuZkBm0K3dGRTMyBob1IiLAY1Gw?e=afnKif)
[Test RFEM6 File](https://burohappold-my.sharepoint.com/:u:/p/arne_martensen/EX3xBIWe-bBGueKDoAsT08MBa9O4JZvhJxJ11GhiIbTDng?e=ZH5VO9)

### Changelog

- Added new Opening partial classes in to the FromRFEM6, ToRFEM6, Create, Read and Update Folder. 
- Added the RFEMLineType Circle and Arc
- Added the attributes Radius, Angle, X_Vector, Y_Vector and Normal to the class RFEMLine

### Additional comments

-When Pushing Surfaces the update does not work yet. So instead of deleting and updating mulitple panels will be generated on top of eachother. The Same is true for openings.  
-When testing for issue #15 please use the attached RFEM6 file to push and pull to. This file should have added Sections and Materials that have not been implemented.

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by staintono — COMMENTED** [review]
PR was checked using the attached scripts. The pushing of surfaces and openings with arc/circle shapes all work correctly. When pulling, only the first few openings are pulled but not all of them, which is not correct. This issues has been discussed and was replicated by Arne to be able to correct it. 
The pushing and pulling in a model with incompatible materials now functions as expected and no longer causes issues.
The code was not reviewed.

**Review by staintono — APPROVED** [review]
Panels and openings with arc/circle can be successfully pushed and pulled. Pushing and pulling of all elements can also be performed with incompatible elements existing in the RFEM model. This was all tested using the provided test scripts as well as some self generated ones. The code was not reviewed

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Pull request merged**
