### PR TITLE
Pushing opeining is triggering error message. 

### LINKED ISSUE #67: Pushing Opening Causes Error

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

The Push of opening was causeing issues due to an null refernce. 
This PR should resolve this issue. 

Closes #67 

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/s/BHoM/EcOa-FWE47hDp_oyl6r1_5IBHiHsx-9rb3o-uwh7mdgbqw?e=QAVCOf)

### Changelog

Remove a line which did cause cause an null references in the ToRFEM6 Opening partial Class.

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Kar-Myl** [comment]
As part of the review:

- The test file was pushed and it did not cause any errors. 
- A comment was added to the panel and it was also created as expected. 
- Code was not reviewed.

**Review by Kar-Myl — APPROVED** [review]

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by Arne-Martensen** [comment]
check ready-to-merge

**Review by Kar-Myl — APPROVED** [review]
Feature was tested on the grasshopper file provided. 

The following tests were performed:

- Pushed the panel and opening to RFEM6.
- Verified the creation of a panel with opening in RFEM6.

Code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
