### PR TITLE
After RFEM6 update RFEM6_Toolkit stopped working. 

### LINKED ISSUE #98: After move to RFEM 6.06.0013 Toolkit Stopped working.
#### Description:

When running the RFEM6_Toolkit with RFEM6.06.00013 the RFEM6_Toolkit stopped working. 

Most likely update of RFEMWebServiceLibrary is necessary

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

After switching to RFEM 6.06.0013, the RFEM6_Toolkit stopped working.
The issue was resolved by updating the referenced Dlubal.RFEMWebServiceLibrary to 6.7.6.
The update of the package caused another issue, as the data structure necessary for pulling nodal results within the C# client had changed. So it was necessary to perform some alterations on that end as well.

Closes #98 

1. Bespoke package has been updated.
2. Reading of the nodal results has been updated.

### Test files

[Test File Folder](https://burohappold.sharepoint.com/:f:/s/BHoM/EuvuS4mATpxHoqQ4AUN2W3IBCX4KCpw7W6fncFRXpMA34A?e=gYmN1W)

Please test the update by: 

1. Open the RFEM File in RFEM6.06.0013 (Please this EXACT version!)
2. Open the GH file and try to pull the results. 
3. Compare the results in RFEM with the ones in GH. 

### Changelog

1. Update of Dlubal.RFEMWebServiceLiabarary
4. Refactroing/Fixing the ExtractNodeReaction() method

### CODE REVIEW

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check null-handling

**Review by Kar-Myl — APPROVED** [review]
The RFEM model was tested on the requested RFEM6 version with the provided grasshopper script. The Nodal results were pulled and then the results were compared to the ones shown in RFEM6. The results match, as expected.

Code was not reviewed.

**Comment by Arne-Martensen** [comment]
@BHoMBot check versioning

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
